language: android
android:
  components:
    - build-tools-22.0.1
    - android-19
	
	# Additional components
	- extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
